name: "Setup poetry dependencies"
description: "Setup Python interpreter and project dependencies."


inputs:
  python-version:
    description: "Version of Python interpreter to setup"
    required: true
    default: "3.8"

  poetry-version:
    description: "Version of Poetry package manager to setup"
    required: true
    default: "1.3.2"

runs:
  using: "composite"

  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Get full Python version
      id: full-python-version
      shell: bash
      run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")

    - name: Cache python packages
      id: cache
      uses: actions/cache@v3
      env:
        cache-name: cache-python-packages
      with:
        path: |
          ~/.cache/pip
          .venv
        key: ${{ steps.full-python-version.outputs.version }}-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      shell: bash
      run: |
        pip install -q poetry==${{ inputs.poetry-version }}
        poetry config virtualenvs.in-project true
        poetry install
